### PR TITLE
Feature/156882167/send in app invites

### PR DESCRIPTION
**Pull request by Orlayhemmy**
#### What does this PR do?
It allows online registered users to send invites to play a game amongst themselves

#### Description of Task to be completed?
add function to track online users on socket.js on the server side
add function to receive data sent by socket on index.js and game.js on the client side
add a notification to alert users when they have received an invite.

#### Any background context you want to provide?
The invite.html page is a mock to test the functionality of the feature and it would be redesigned when the gaming screen is designed.

#### What are the relevant pivotal tracker stories?
Story Id #156882167

### CODE REVIEW

**Review by Spectrumsun — COMMENTED** [review]
Good Job. But I notice some issues when testing the PR on Heroku

1. When I search for users online. I see my username on the list of the result. I believe that is not a good user experience. I should only see other users name and not mine 

2. I also notice that I can send myself an invite. to play a game. This can leave the user confused when using the feature

3. According to your PR the feature is for registered users but when I played as a guess I can still see the feature available for me. Does that mean the feature is available for everyone??

4. Also when I try to search for online users as a guess the application crashed on Heroku and log out " TypeError: Cannot read property 'emit' of undefined".  which I think is a bug.

Please look into this issues. Well done.

**Review by kenoseni — COMMENTED** [review]
After deploying your branch on Heroku, I noticed that in searching for users online your implementation does not search for all users because at a point Heroku crashes when sending invites to online gamers. I also noticed that if an invite is successfully sent and the game is joined and later abandoned, other gamers can't send other invites to users because the application crashes. Please see Sunday's review for specifics because I totally agree with his review since we tested the application together.

**Comment by kenoseni** [comment]
Also, as an added comment, try to fix the coverall issue.

**Comment by Orlayhemmy** [comment]
I have rectified all the issues pointed out

**Pull request merged**
